### ISSUE TITLE
SendCurrentLine will not send "\n" to the command

### ISSUE THREAD

**Issue by living1069** [sillybun/vim-repl#23]
**Describe the bug**
When using \w, it will not send "\n" after current line. 

**Desktop (please complete the following information):**

 - vim --version
Terminal and  timers  are all supported.

**Additional context**
windows 10
vim 8.1 with terminal and timers supported.
vim-repl, 2019.8.17

**Comment by sillybun** [comment]
Can you tell me the result of `:REPLDebugInfo`? I have test the plugin on my windows pc and it's OK.

**Comment by sillybun** [comment]
Thank you for reporting this bug it has been fixed.

**Comment by living1069** [comment]
**Describe the bug**
This is still not working on windows 10. This fix does not only fail to send "\n" of a command to terminal but also a blank line which only contain "\n" in comparison of previous version. 
 

**Screenshots**
![image](https://user-images.githubusercontent.com/12094643/63645290-61379880-c72d-11e9-9ba6-7f10d545e8a2.png)


**Desktop (please complete the following information):**

 - vim --version
![image](https://user-images.githubusercontent.com/12094643/63645296-77ddef80-c72d-11e9-985e-589e386ccf97.png)
![image](https://user-images.githubusercontent.com/12094643/63645298-8926fc00-c72d-11e9-99e1-203de1ab7eb5.png)

 - result of `:REPLDebugInfo`
![image](https://user-images.githubusercontent.com/12094643/63645305-a22fad00-c72d-11e9-8d34-181a96d566fa.png)

**Additional context**
windows 10
gvim 8.1

Note: I aslo removed all the configure options and only kept the vim-REPL plugin. But no luck appeared. The fix seemed to disable sending and "\n" to terminal. Below is the REPL configure:
let g:repl_program = {
            \   'default': 'cmd.exe',
            \   }
let g:repl_predefine_python = {
            \   'numpy': 'import numpy as np',
            \   'matplotlib': 'from matplotlib import pyplot as plt'
            \   }
let g:repl_cursor_down = 1
let g:repl_python_automerge = 1
let g:repl_ipython_version = '7'
nnoremap <leader>r :REPLToggle<Cr>
autocmd Filetype python nnoremap <F9> <Esc>:REPLDebugStopAtCurrentLine<Cr>
autocmd Filetype python nnoremap <F10> <Esc>:REPLPDBN<Cr>
autocmd Filetype python nnoremap <F11> <Esc>:REPLPDBS<Cr>
let g:repl_position = 0

**Comment by sillybun** [comment]
I see, the reason for this thix bug is that sometimes you have to send `\r\n` to termianl and sometimes it has to be `\n` on Windows, which depends on the program opened in repl environment. I will fix it right now.

**Comment by sillybun** [comment]
It has been fixed now. You can test it on your machine now.

**Comment by living1069** [comment]
Thanks. It works!
